Feature/setup sql alchemy
boi-talk/api pull request #1
Opened 2022-12-28 01:51 UTC by kevintrinh388

finished setting up sqlalchemy

2022-12-29 03:00 UTC, kphan32 requested changes
🤔

2022-12-29 03:00 UTC, kphan32 commented on README.md
> +You gun need to run database locally cus tech lead don't wanna make a database for me
🤔

2022-12-29 03:00 UTC, kphan32 commented on app.py
> +  # db.session.commit()
🤔

2022-12-29 03:00 UTC, kphan32 commented on app.py
> +    db.create_all()
need to create db migrations-- i think this will just create tables as needed which isnt what we want

2022-12-29 03:00 UTC, kphan32 commented on app.py
> +  app.run(debug=True, host='0.0.0.0', port=port)
ideally this is only run in prod, so we don't want `Debug` to be true (this block of code isnt run when running `flask run`)

2022-12-29 03:00 UTC, kphan32 commented on app.py
> +      "password":user.password
nit: formatting. we might add some linter/formatter later

2022-12-29 03:00 UTC, kphan32 commented on database.py
> +load_dotenv(find_dotenv())
this should go into `app`

2022-12-29 03:00 UTC, kphan32 commented on database.py
> +    db_url = db_url.replace("postgres://", "postgresql://", 1)
i think the `replace` call will do nothing if it doesnt start with it, so the if might be redundant

2022-12-29 03:00 UTC, kphan32 commented on models.py
> +    password = db.Column(db.String(256), nullable=True)
why is the password nullable 🤔

2022-12-29 03:00 UTC, kphan32 commented on models.py
> +db.create_all()
does this get called twice?

2022-12-29 03:00 UTC, kphan32 commented on README.md
> +You gun need to run database locally cus tech lead don't wanna make a database for me
should also leave some instructions on creating the env file. i personally create a `.env.example` file that will be committed with an example of what env vars should be setup. also modify the `.gitignore` to ignore the `.env` file

2022-12-29 03:16 UTC, kevintrinh388 commented on app.py
> +    db.create_all()
i still dont know what this means btw

2022-12-29 03:49 UTC, kevintrinh388 commented on app.py
> +    db.create_all()
nvm using flask-migrate i tink i got it

2022-12-29 04:11 UTC, kphan32 requested changes

2022-12-29 04:11 UTC, kphan32 commented on README.md
> +`export DATABASE_URL="PUT YOUR LOCAL DATABASE URL HERE"`
```suggestion
`DATABASE_URL="PUT YOUR LOCAL DATABASE URL HERE"`
```

2022-12-29 04:11 UTC, kphan32 commented on app.py
> +load_dotenv(find_dotenv())
need to load dotenv first before using env vars

2022-12-29 04:11 UTC, kphan32 commented on app.py
> +app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
🤔

2022-12-29 04:11 UTC, kphan32 commented on migrations/versions/a4098101f6f9_initial_migration.py
> +    )
these look backwards

2022-12-29 04:11 UTC, kphan32 commented on migrations/versions/a4098101f6f9_initial_migration.py
> +    )
nit: formatting

2022-12-29 04:11 UTC, kphan32 commented on migrations/versions/a4098101f6f9_initial_migration.py
> +    sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
why is password nullable 🤔

2022-12-30 16:34 UTC, kphan32 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Setup SQL Alchemy](https://trello.com/c/Klz9sVSF/6-setup-sql-alchemy)

2022-12-30 17:59 UTC, kphan32 approved these changes
lgtm :+1:

2022-12-30 23:47 UTC, kevintrinh388 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Setup SQL Alchemy](https://trello.com/c/Klz9sVSF/6-setup-sql-alchemy)

2022-12-30 23:48 UTC, merged