add register route to create new users, add error handling for all cases
boi-talk/api pull request #4
Opened 2022-12-31 00:58 UTC by kevintrinh388

Added register route, added error handling to handle all cases/scenarios

2022-12-31 00:58 UTC, kevintrinh388 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create register route](https://trello.com/c/lJZBCHy2/7-create-register-route)

2022-12-31 02:15 UTC, kphan32 requested changes

2022-12-31 02:15 UTC, kphan32 commented on app.py
> +        return "Email and password are empty",400
nit: formatting

2022-12-31 02:15 UTC, kphan32 commented on app.py
> +    if len(email)==0 and len(password)==0:
are empty values actually passed as empty strings? or are they `None`/do not exist within the dictionary?

2022-12-31 02:15 UTC, kphan32 commented on app.py
> +        return jsonify({"error":"invalid password"}), 400
this already gets checked

2022-12-31 02:15 UTC, kphan32 commented on app.py
> +        return "Email and password are empty",400
i would make the if an `or` and rewrite the error to be `must provide email and password`

2022-12-31 02:15 UTC, kphan32 commented on app.py
> +        return "Email and password are empty",400
also, make this into JSON like below

2022-12-31 02:15 UTC, kphan32 commented on app.py
> +        return "User with email already exists", 409
ideally this check would be done by the database (ie when creating, it raises an error about validating a unique-ness index)

2022-12-31 02:15 UTC, kphan32 commented on app.py
> +    hashed_pass = hashlib.sha256(str.encode(password)).hexdigest()
use bcrypt to make your life easier : )

2022-12-31 02:21 UTC, kevintrinh388 commented on app.py
> +    hashed_pass = hashlib.sha256(str.encode(password)).hexdigest()
done

2022-12-31 03:17 UTC, kevintrinh388 commented on app.py
> +        return jsonify({"error":"invalid password"}), 400
done

2022-12-31 03:17 UTC, kevintrinh388 commented on app.py
> +        return "Email and password are empty",400
done

2022-12-31 03:25 UTC, kevintrinh388 commented on app.py
> +        return "Email and password are empty",400
done

2022-12-31 03:27 UTC, kevintrinh388 commented on app.py
> +    if len(email)==0 and len(password)==0:
depends on what the frontend could possibly send, I have now covered both scenarios
1. the request has no email field OR no password field
2. the request's email OR password field is null OR empty string
done

2022-12-31 03:45 UTC, kevintrinh388 commented on app.py
> +        return "User with email already exists", 409
done

2023-01-06 04:06 UTC, kphan32 requested changes

2023-01-06 04:06 UTC, kphan32 commented on app.py
> +        return jsonify({"error":"User with email already exists"}), 409
can we verify that this is an actual unique key restraint error? it looks like it could be any error and we'd respond with a 409

2023-01-06 04:06 UTC, kphan32 commented on app.py
> +        return jsonify({"error":"User with email already exists"}), 409
(in case of an unrelated DB failure, return 500 and log the error)

2023-01-06 04:06 UTC, kphan32 commented on app.py
> +        return jsonify({"error":"User with email already exists"}), 409
(or maybe even just re-raise the error? not sure how flask will handle that though)

2023-01-06 23:30 UTC, kphan32 approved these changes
lgtm :+1:

2023-01-06 23:31 UTC, merged